# Welcome to Jekyll!
title: Piranha
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/horikomi" # the subpath of your site, e.g. /blog
url: "https://trantue.github.io" # the base hostname & protocol for your site, e.g. http://example.com

sass:
 sass dir: _sass
 
include: ['_pages']

paginate: 3
paginate_path: "/blog/page:num"


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
